exclude = [
  "@ref",
  "^https://github.com/.*/releases/tag/v.*$",
  "^https://doi.org/FIXME$",
  "^https://tmigot.github.io/TimerNLPModels.jl/stable$",
  "zenodo.org/badge/DOI/FIXME$"
]

exclude_path = [
  "docs/build"
]
